import { AISummaryResult } from "@/types";
import { formatDistanceToNow } from "date-fns";

interface Props {
  summary: AISummaryResult;
  ticker: string;
}

export default function AISummaryCard({ summary, ticker }: Props) {
  const timeAgo = formatDistanceToNow(new Date(summary.generatedAt), {
    addSuffix: true,
  });

  return (
    <div className="card relative overflow-hidden">
      {/* gradient accent */}
      <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-green-500 to-emerald-400 rounded-t-2xl" />

      {/* Header */}
      <div className="flex items-center gap-2 mb-4 pt-1">
        <span className="text-lg">🤖</span>
        <span className="text-xs font-semibold uppercase tracking-widest text-gray-400">
          AI Summary
        </span>
        {summary.cached && (
          <span className="ml-auto text-xs text-gray-600 font-mono">cached</span>
        )}
      </div>

      <h2 className="text-xl font-bold leading-snug mb-4">{summary.headline}</h2>

      {/* Key reasons */}
      {summary.keyReasons.length > 0 && (
        <ul className="mb-5 space-y-2">
          {summary.keyReasons.map((reason, i) => (
            <li key={i} className="flex gap-2 text-sm text-gray-300">
              <span className="text-green-400 mt-0.5 shrink-0">•</span>
              <span>{reason}</span>
            </li>
          ))}
        </ul>
      )}

      {/* Full summary */}
      <p className="text-sm text-gray-400 leading-relaxed">{summary.summary}</p>

      <p className="text-xs text-gray-600 mt-4">
        Generated by GPT-4o-mini · {timeAgo}
      </p>
    </div>
  );
}
